/* Geographic source of truth for the life-map. Plain-script + Node compatible. */
(function (root, factory) {
  var model = factory();
  if (typeof module === 'object' && module.exports) { module.exports = model; }
  if (root) { root.ATLAS_MODEL = model; }
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

  var SOURCE = 'Herocards historical-place curation v1, 2026-08-20';

  function place(label, modernName, longitude, latitude, precision, confidence, note) {
    return {
      label: label,
      modernName: modernName || '',
      coordinates: [longitude, latitude],
      precision: precision,
      confidence: confidence,
      source: SOURCE,
      note: note || ''
    };
  }

  var places = {
    handan: place('邯郸', '河北邯郸', 114.49, 36.62, 'city', 'high'),
    xianyang: place('咸阳', '陕西咸阳', 108.71, 34.33, 'city', 'high'),
    zhongyuan: place('中原', '黄河中下游地区', 113.50, 34.00, 'region', 'low', '叙事区域，不表示单一城市'),
    taishan: place('泰山', '山东泰安泰山', 117.10, 36.25, 'site', 'high'),
    langyatai: place('琅琊', '山东青岛琅琊台', 120.02, 35.58, 'site', 'medium', '秦始皇巡游所至琅琊台'),
    shaqiu: place('沙丘', '河北广宗沙丘平台一带', 115.14, 37.06, 'region', 'medium'),
    changan: place('长安', '陕西西安', 108.94, 34.34, 'city', 'high'),
    fenyin: place('汾阴', '山西万荣', 110.84, 35.42, 'city', 'medium'),
    huzi: place('瓠子', '河南濮阳黄河故道一带', 115.03, 35.76, 'region', 'low'),
    ganquan: place('甘泉', '陕西淳化甘泉宫遗址一带', 108.58, 34.80, 'site', 'medium'),
    wuzhegong: place('五柞宫', '陕西周至一带', 108.22, 34.16, 'region', 'medium'),
    wugong: place('武功', '陕西武功', 108.21, 34.26, 'city', 'high'),
    jinyang: place('晋阳', '山西太原晋阳古城', 112.49, 37.78, 'site', 'high'),
    luoyang: place('洛阳', '河南洛阳', 112.45, 34.62, 'city', 'high'),
    cuiweigong: place('翠微宫', '陕西终南山北麓', 108.58, 33.86, 'region', 'medium'),
    wenshui: place('文水', '山西文水', 112.03, 37.44, 'city', 'high'),
    mingtang_luoyang: place('明堂', '洛阳武周明堂遗址', 112.45, 34.68, 'site', 'high'),
    shangyanggong: place('上阳宫', '洛阳上阳宫遗址', 112.40, 34.68, 'site', 'medium'),
    onon_river: place('斡难河', '蒙古国鄂嫩河流域', 111.60, 48.90, 'region', 'medium'),
    burkhan_khaldun: place('不儿罕山', '蒙古国肯特山脉', 109.00, 48.75, 'region', 'medium'),
    onon_source: place('斡难河源', '蒙古国鄂嫩河上游', 109.80, 48.80, 'region', 'medium'),
    samarkand: place('撒马尔罕', '乌兹别克斯坦撒马尔罕', 66.97, 39.65, 'city', 'high'),
    liupanshan: place('六盘山', '宁夏六盘山一带', 106.20, 35.50, 'region', 'medium'),
    forbidden_city: place('紫禁城', '北京故宫', 116.397, 39.918, 'site', 'high'),
    jiangnan: place('江南', '长江下游地区', 119.50, 30.50, 'region', 'low', '六次南巡的叙事区域'),
    duolun: place('多伦', '内蒙古多伦', 116.49, 42.20, 'city', 'high'),
    kherlen: place('克鲁伦河', '蒙古国克鲁伦河流域', 113.50, 47.50, 'region', 'medium'),
    rehe: place('热河', '河北承德', 117.96, 40.95, 'city', 'high'),
    changchunyuan: place('畅春园', '北京海淀畅春园遗址', 116.30, 39.99, 'site', 'medium'),
    langya_yangdu: place('琅琊', '山东沂南阳都故城一带', 118.47, 35.55, 'region', 'medium', '诸葛亮籍贯所指琅琊阳都'),
    longzhong: place('隆中', '湖北襄阳古隆中', 112.02, 32.03, 'site', 'high'),
    chibi: place('赤壁', '湖北赤壁古战场一带', 113.89, 29.71, 'region', 'medium', '古战场具体范围存在争议'),
    chengdu: place('成都', '四川成都', 104.07, 30.57, 'city', 'high'),
    wuzhangyuan: place('五丈原', '陕西岐山五丈原', 107.62, 34.34, 'site', 'high'),
    tangyin: place('汤阴', '河南汤阴', 114.36, 35.92, 'city', 'high'),
    jiankang: place('建康', '江苏南京', 118.80, 32.06, 'city', 'high'),
    yancheng: place('郾城', '河南漯河郾城', 113.94, 33.84, 'city', 'high'),
    zhuxianzhen: place('朱仙镇', '河南开封朱仙镇', 114.17, 34.32, 'city', 'high'),
    fengboting: place('风波亭', '浙江杭州', 120.16, 30.25, 'site', 'medium'),
    huaiyin: place('淮阴', '江苏淮安', 119.02, 33.61, 'city', 'high'),
    hanzhong: place('汉中', '陕西汉中', 107.03, 33.07, 'city', 'high'),
    jingxing: place('井陉', '河北井陉', 114.14, 38.03, 'city', 'high'),
    gaixia: place('垓下', '安徽灵璧垓下遗址一带', 117.55, 33.54, 'site', 'medium'),
    changle_palace: place('长乐宫', '西安汉长安城遗址', 109.01, 34.27, 'site', 'high'),
    mulan_homeland: place('故乡', '木兰故里争议区域', 114.00, 36.50, 'unknown', 'low', '文学叙事地点，多地存在故里说'),
    yellow_river: place('黄河', '黄河中游叙事锚点', 111.50, 35.00, 'region', 'low'),
    yanshan: place('燕山', '燕山山脉', 117.50, 40.50, 'region', 'medium'),
    mingtang_mulan: place('明堂', '《木兰诗》朝廷叙事锚点', 112.00, 38.00, 'unknown', 'low', '不等同于武周洛阳明堂'),
    dengzhou: place('登州', '山东蓬莱登州府', 120.75, 37.82, 'city', 'high'),
    yiwu: place('义乌', '浙江义乌', 120.08, 29.31, 'city', 'high'),
    taizhou: place('台州', '浙江台州', 121.42, 28.66, 'city', 'high'),
    jizhou: place('蓟州', '天津蓟州', 117.41, 40.05, 'city', 'high'),
    penglai: place('蓬莱', '山东蓬莱', 120.76, 37.81, 'city', 'high'),
    luling: place('庐陵', '江西吉安', 114.98, 27.11, 'city', 'high'),
    linan: place('临安', '浙江杭州', 120.16, 30.25, 'city', 'high'),
    wupoling: place('五坡岭', '广东海丰五坡岭', 115.32, 22.97, 'site', 'high'),
    dadu: place('大都', '北京', 116.40, 39.90, 'city', 'high'),
    chaishi: place('柴市', '北京菜市口一带', 116.37, 39.88, 'site', 'medium'),
    gongxian: place('巩县', '河南巩义', 113.02, 34.75, 'city', 'high'),
    xiangjiang_dufu: place('湘江', '岳阳至长沙水域', 113.13, 29.37, 'region', 'low', '杜甫晚年舟行叙事锚点'),
    meishan: place('眉山', '四川眉山', 103.85, 30.08, 'city', 'high'),
    bianjing: place('汴京', '河南开封', 114.31, 34.80, 'city', 'high'),
    huangzhou: place('黄州', '湖北黄冈', 114.87, 30.45, 'city', 'high'),
    hangzhou: place('杭州', '浙江杭州', 120.16, 30.25, 'city', 'high'),
    danzhou: place('儋州', '海南儋州', 109.58, 19.52, 'city', 'high'),
    changzhou: place('常州', '江苏常州', 119.97, 31.81, 'city', 'high'),
    zhangqiu: place('章丘', '山东济南章丘', 117.53, 36.72, 'city', 'high'),
    qingzhou: place('青州', '山东青州', 118.48, 36.68, 'city', 'high'),
    jinhua: place('金华', '浙江金华', 119.65, 29.09, 'city', 'high'),
    linyi: place('临沂', '山东临沂', 118.36, 35.10, 'city', 'high'),
    kuaiji: place('会稽', '浙江绍兴', 120.58, 30.00, 'city', 'high'),
    shanxian: place('剡县', '浙江嵊州', 120.83, 29.59, 'city', 'high'),
    jiangning: place('江宁', '江苏南京', 118.80, 32.06, 'city', 'high'),
    suanshikou: place('蒜市口', '北京崇文门外一带', 116.43, 39.89, 'site', 'medium'),
    xishan: place('西山', '北京西山', 116.10, 39.98, 'region', 'medium'),
    beijing: place('北京', '北京', 116.41, 39.90, 'city', 'high'),
    xiongnu: place('匈奴', '蒙古高原南部叙事锚点', 104.00, 43.00, 'region', 'low'),
    dayuan: place('大宛', '费尔干纳盆地', 70.94, 40.53, 'region', 'medium'),
    wusun: place('乌孙', '伊犁河谷一带', 80.00, 43.50, 'region', 'medium'),
    goushi: place('缑氏', '河南洛阳偃师一带', 112.78, 34.73, 'city', 'medium'),
    gaochang: place('高昌', '新疆吐鲁番高昌故城', 89.54, 42.85, 'site', 'high'),
    nalanda: place('那烂陀', '印度那烂陀遗址', 85.44, 25.14, 'site', 'high'),
    kannauj: place('曲女城', '印度卡瑙杰', 79.92, 27.05, 'city', 'high'),
    kunyang: place('昆阳', '云南昆明晋宁区', 102.60, 24.68, 'city', 'high'),
    liujiagang: place('刘家港', '江苏太仓浏河', 121.13, 31.45, 'site', 'medium'),
    calicut: place('古里', '印度科泽科德', 75.78, 11.26, 'city', 'high'),
    hormuz: place('忽鲁谟斯', '伊朗霍尔木兹岛', 56.45, 27.06, 'city', 'high'),
    malindi: place('麻林', '肯尼亚马林迪', 40.12, -3.22, 'city', 'medium'),
    zhenghe_return: place('归途', '古里附近海域', 75.78, 11.26, 'region', 'low', '归途去世说法存在差异'),
    jiangyin: place('江阴', '江苏江阴', 120.28, 31.92, 'city', 'high'),
    tiantaishan: place('天台山', '浙江天台山', 121.05, 29.14, 'site', 'high'),
    huangshan: place('黄山', '安徽黄山', 118.17, 30.13, 'site', 'high'),
    xiangjiang_xuxiake: place('湘江', '湖南衡阳至长沙水域', 112.90, 27.80, 'region', 'low', '徐霞客舟行叙事锚点'),
    jizushan: place('鸡足山', '云南宾川鸡足山', 100.38, 25.96, 'site', 'high'),
    qiao_county: place('谯县', '安徽亳州', 115.78, 33.84, 'city', 'high'),
    guangling: place('广陵', '江苏扬州', 119.41, 32.39, 'city', 'high'),
    xuchang: place('许昌', '河南许昌', 113.85, 34.04, 'city', 'high'),
    xudu_prison: place('许都狱中', '河南许昌', 113.86, 34.03, 'site', 'medium'),
    louxian: place('娄县', '江苏昆山一带', 120.98, 31.38, 'city', 'medium'),
    leyouyuan: place('乐游苑', '陕西西安乐游原', 109.00, 34.23, 'site', 'medium'),
    suiye: place('碎叶', '吉尔吉斯斯坦托克马克一带', 75.30, 42.84, 'region', 'medium'),
    shuzhong: place('蜀中', '四川盆地西部', 104.20, 31.00, 'region', 'low'),
    manyou: place('漫游', '梁宋齐鲁吴越叙事锚点', 116.50, 34.00, 'region', 'low'),
    yelang: place('夜郎', '贵州桐梓一带', 106.82, 28.13, 'region', 'low', '李白流放夜郎的具体指向存在讨论'),
    dangtu: place('当涂', '安徽当涂', 118.50, 31.57, 'city', 'high')
  };

  /* Transitional georeferencing for the original painterly image. The target
     x/y values are normalized image coordinates selected from recognizable
     geography. Areas outside this control mesh are deliberately unsupported. */
  var legacyCalibration = {
    image: { src: 'assets/atlas/map.webp', width: 2496, height: 1664 },
    controlPoints: {
      samarkand: { placeId: 'samarkand', x: 0.03, y: 0.22 },
      suiye: { placeId: 'suiye', x: 0.08, y: 0.26 },
      gaochang: { placeId: 'gaochang', x: 0.18, y: 0.28 },
      kherlen: { placeId: 'kherlen', x: 0.50, y: 0.10 },
      beijing: { placeId: 'beijing', x: 0.64, y: 0.21 },
      changan: { placeId: 'changan', x: 0.50, y: 0.34 },
      taishan: { placeId: 'taishan', x: 0.65, y: 0.31 },
      chengdu: { placeId: 'chengdu', x: 0.40, y: 0.50 },
      jiankang: { placeId: 'jiankang', x: 0.63, y: 0.48 },
      hangzhou: { placeId: 'hangzhou', x: 0.66, y: 0.54 },
      kunyang: { placeId: 'kunyang', x: 0.40, y: 0.60 },
      danzhou: { placeId: 'danzhou', x: 0.55, y: 0.72 },
      nalanda: { placeId: 'nalanda', x: 0.25, y: 0.85 },
      kannauj: { placeId: 'kannauj', x: 0.20, y: 0.80 }
    },
    triangles: [
      ['samarkand', 'suiye', 'gaochang'],
      ['samarkand', 'gaochang', 'kannauj'],
      ['gaochang', 'kherlen', 'changan'],
      ['kherlen', 'beijing', 'changan'],
      ['changan', 'beijing', 'taishan'],
      ['changan', 'taishan', 'jiankang'],
      ['changan', 'jiankang', 'chengdu'],
      ['chengdu', 'jiankang', 'kunyang'],
      ['jiankang', 'hangzhou', 'kunyang'],
      ['hangzhou', 'danzhou', 'kunyang'],
      ['gaochang', 'changan', 'kannauj'],
      ['kannauj', 'changan', 'kunyang'],
      ['kannauj', 'kunyang', 'nalanda'],
      ['nalanda', 'kunyang', 'danzhou']
    ]
  };

  return {
    version: 1,
    asset: {
      src: 'assets/atlas/map-projected.svg',
      skinSrc: 'assets/atlas/map-terrain-natural-earth-v2.webp',
      skinStyle: 'natural-earth-srtm-qinglu-v2',
      terrainSource: 'natural-earth-shaded-relief-srtm-plus',
      terrainManifest: 'assets/atlas/terrain-manifest.json',
      projectionId: 'web-mercator-eurasia-indian-ocean-v1',
      attribution: 'Natural Earth Shaded Relief and vectors, public domain'
    },
    projection: {
      id: 'web-mercator-eurasia-indian-ocean-v1',
      type: 'mercator',
      width: 2400,
      height: 1600,
      padding: 64,
      bounds: { west: 32, south: -12, east: 145, north: 58 }
    },
    legacyCalibration: legacyCalibration,
    places: places,
    routes: {
      qinshihuang: ['handan', 'xianyang', 'zhongyuan', 'taishan', 'langyatai', 'shaqiu'],
      hanwudi: ['changan', 'fenyin', 'taishan', 'huzi', 'ganquan', 'wuzhegong'],
      tangtaizong: ['wugong', 'jinyang', 'luoyang', 'changan', 'cuiweigong'],
      wuzetian: ['wenshui', 'changan', 'luoyang', 'mingtang_luoyang', 'shangyanggong'],
      chengjisihan: ['onon_river', 'burkhan_khaldun', 'onon_source', 'samarkand', 'liupanshan'],
      kangxi: ['forbidden_city', 'jiangnan', 'duolun', 'kherlen', 'rehe', 'changchunyuan'],
      zhugeliang: ['langya_yangdu', 'longzhong', 'chibi', 'chengdu', 'wuzhangyuan'],
      yuefei: ['tangyin', 'jiankang', 'yancheng', 'zhuxianzhen', 'fengboting'],
      hanxin: ['huaiyin', 'hanzhong', 'jingxing', 'gaixia', 'changle_palace'],
      huamulan: ['mulan_homeland', 'yellow_river', 'yanshan', 'mingtang_mulan', 'mulan_homeland'],
      qijiguang: ['dengzhou', 'yiwu', 'taizhou', 'jizhou', 'penglai'],
      wentianxiang: ['luling', 'linan', 'wupoling', 'dadu', 'chaishi'],
      dufu: ['gongxian', 'taishan', 'changan', 'chengdu', 'xiangjiang_dufu'],
      sushi: ['meishan', 'bianjing', 'huangzhou', 'hangzhou', 'danzhou', 'changzhou'],
      liqingzhao: ['zhangqiu', 'qingzhou', 'jiankang', 'jinhua', 'linan'],
      wangxizhi: ['linyi', 'jiankang', 'kuaiji', 'shanxian'],
      caoxueqin: ['jiangning', 'suanshikou', 'xishan', 'beijing'],
      zhangqian: ['changan', 'xiongnu', 'dayuan', 'wusun', 'changan'],
      xuanzang: ['goushi', 'changan', 'gaochang', 'nalanda', 'kannauj', 'changan'],
      zhenghe: ['kunyang', 'liujiagang', 'calicut', 'hormuz', 'malindi', 'zhenghe_return'],
      xuxiake: ['jiangyin', 'tiantaishan', 'huangshan', 'xiangjiang_xuxiake', 'jizushan', 'jiangyin'],
      huatuo: ['qiao_county', 'guangling', 'xuchang', 'xudu_prison'],
      zuchongzhi: ['jiankang', 'louxian', 'leyouyuan', 'jiankang'],
      libai: ['suiye', 'shuzhong', 'changan', 'manyou', 'yelang', 'dangtu']
    }
  };
});
